import { join, normalize, sep } from "node:path";
// @ts-expect-error generated by `vite build`, ships without type declarations
import handler from "./dist/server/server.js";

const CLIENT_DIR = join(import.meta.dir, "dist", "client");
const IMMUTABLE_CACHE = "public, max-age=31536000, immutable";

async function serveStatic(pathname: string): Promise<Response | null> {
	let decoded: string;
	try {
		decoded = decodeURIComponent(pathname);
	} catch {
		return null;
	}
	const filePath = normalize(join(CLIENT_DIR, decoded));
	if (!filePath.startsWith(CLIENT_DIR + sep)) {
		return null;
	}
	const file = Bun.file(filePath);
	if (!(await file.exists())) {
		return null;
	}
	return new Response(file, {
		headers: pathname.startsWith("/assets/")
			? { "Cache-Control": IMMUTABLE_CACHE }
			: undefined,
	});
}

const server = Bun.serve({
	port: Number(process.env.PORT ?? 3000),
	async fetch(request) {
		if (request.method === "GET" || request.method === "HEAD") {
			const staticResponse = await serveStatic(new URL(request.url).pathname);
			if (staticResponse) {
				return staticResponse;
			}
		}
		return handler.fetch(request);
	},
});

console.log(`Server running at http://localhost:${server.port}`);
