import { type AuthoredExercise, p } from "./practice-authoring";

export const selfJoinsPractice: Record<string, AuthoredExercise[]> = {
	"self-joins": [
		p(
			"pool-self-album-chronology",
			"Earlier and later releases",
			"For albums by the same artist, return the earlier **title** as **earlier_album** and later title as **later_album**. Sort by both titles.",
			"Match artist_id, then require the first release_year to be lower than the second.",
			"SELECT earlier.title AS earlier_album, later.title AS later_album FROM albums AS earlier JOIN albums AS later ON earlier.artist_id = later.artist_id AND earlier.release_year < later.release_year ORDER BY earlier_album, later_album",
			true,
			"surface",
			["self-join", "column-comparison", "ordering"],
		),
		p(
			"pool-self-price-pairs",
			"Cheaper album in the same genre",
			"Return album pairs in the same genre where one is cheaper. Show the cheaper **title** as **cheaper_album** and the other as **costlier_album**, sorted by both.",
			"Join albums to itself on genre and compare price across aliases.",
			"SELECT cheaper.title AS cheaper_album, costlier.title AS costlier_album FROM albums AS cheaper JOIN albums AS costlier ON cheaper.genre = costlier.genre AND cheaper.price < costlier.price ORDER BY cheaper_album, costlier_album",
			true,
			"surface",
			["self-join", "column-comparison", "ordering"],
		),
		p(
			"pool-self-consecutive-longer",
			"When the next track is longer",
			"Return adjacent track pairs where the next track is longer. Show **current_track**, **next_track**, and added seconds as **extra_seconds**.",
			"Self join tracks by album and consecutive track_number, then compare durations.",
			"SELECT current.title AS current_track, following.title AS next_track, following.duration_seconds - current.duration_seconds AS extra_seconds FROM tracks AS current JOIN tracks AS following ON following.album_id = current.album_id AND following.track_number = current.track_number + 1 WHERE following.duration_seconds > current.duration_seconds ORDER BY current.album_id, current.track_number",
			true,
			"surface",
			["self-join", "sequence", "expressions", "ordering"],
		),
		p(
			"pool-self-repeat-buyers",
			"Two purchases by one customer",
			"Return every pair of purchase dates for the same customer. Show **customer_id**, earlier date as **first_date**, later date as **second_date**. Do not pair a purchase with itself.",
			"Join purchases to itself on customer_id and use first.id < second.id.",
			"SELECT first.customer_id, first.purchase_date AS first_date, second.purchase_date AS second_date FROM purchases AS first JOIN purchases AS second ON first.customer_id = second.customer_id AND first.id < second.id ORDER BY first.customer_id, first_date, second_date",
			true,
			"surface",
			["self-join", "pairs", "ordering"],
		),
		p(
			"pool-self-same-day-basket",
			"Albums bought together",
			"Find album pairs bought by one customer on the same date. Return **customer_id**, lower album id as **album_one**, and higher album id as **album_two**.",
			"Self join purchases on customer and date, then order the pair with album_id < album_id.",
			"SELECT first.customer_id, first.album_id AS album_one, second.album_id AS album_two FROM purchases AS first JOIN purchases AS second ON first.customer_id = second.customer_id AND first.purchase_date = second.purchase_date AND first.album_id < second.album_id",
			false,
			"neighbour",
			["self-join", "composite-condition", "pairs"],
		),
		p(
			"pool-self-country-seniority",
			"Who formed first",
			"For artist pairs from the same country, show the earlier act as **older_act** and later act as **newer_act**.",
			"Match country and compare formed_year across the two aliases.",
			"SELECT older.name AS older_act, newer.name AS newer_act FROM artists AS older JOIN artists AS newer ON older.country = newer.country AND older.formed_year < newer.formed_year",
			false,
			"neighbour",
			["self-join", "column-comparison"],
		),
		p(
			"pool-self-track-pairs",
			"Every pair on an album",
			"For each album with multiple tracks, list each track pair once. Return **album_id**, **track_one**, and **track_two**, sorted by album and titles.",
			"Use first.id < second.id so mirrored pairs and self-pairs disappear.",
			"SELECT first.album_id, first.title AS track_one, second.title AS track_two FROM tracks AS first JOIN tracks AS second ON first.album_id = second.album_id AND first.id < second.id ORDER BY first.album_id, track_one, track_two",
			true,
			"neighbour",
			["self-join", "pairs", "ordering"],
		),
		p(
			"pool-self-no-mirrors",
			"USA pair, exactly once",
			"Return the two USA artist names as **artist_one** and **artist_two**, in one row only.",
			"Different ids removes self-pairs but still gives both directions. Use a.id < b.id.",
			"SELECT a.name AS artist_one, b.name AS artist_two FROM artists AS a JOIN artists AS b ON a.country = 'USA' AND b.country = 'USA' AND a.id < b.id",
			false,
			"trap",
			["self-join", "duplicates", "pairs"],
		),
		p(
			"pool-self-adjacent-only",
			"Only the immediate next track",
			"Return **current_track** and **next_track** for immediate neighbors on the same album. Do not include tracks two positions apart.",
			"Match next.track_number to current.track_number + 1, not merely a greater number.",
			"SELECT current.title AS current_track, following.title AS next_track FROM tracks AS current JOIN tracks AS following ON current.album_id = following.album_id AND following.track_number = current.track_number + 1 ORDER BY current.album_id, current.track_number",
			true,
			"trap",
			["self-join", "sequence", "exact-boundary"],
		),
		p(
			"pool-self-cross-genre-pairs",
			"Every unique genre pairing",
			"Create every unordered pair of different album genres. Return **genre_one** and **genre_two** once each, alphabetically.",
			"Start from two distinct genre sets and use first.genre < second.genre to choose one direction.",
			"SELECT first.genre AS genre_one, second.genre AS genre_two FROM (SELECT DISTINCT genre FROM albums) AS first CROSS JOIN (SELECT DISTINCT genre FROM albums) AS second WHERE first.genre < second.genre ORDER BY genre_one, genre_two",
			true,
			"trap",
			["self-join", "cross-join", "distinct", "pairs"],
		),
	],
};
