import { type AuthoredExercise, p } from "./practice-authoring";

export const windowRankingPractice: Record<string, AuthoredExercise[]> = {
	"window-ranking": [
		p(
			"pool-rank-release-years",
			"Newest release ranks",
			"Show album **title**, **release_year**, and dense newest-first rank as **year_rank**. Sort by rank then title.",
			"DENSE_RANK gives consecutive ranks when years tie.",
			"SELECT title, release_year, DENSE_RANK() OVER (ORDER BY release_year DESC) AS year_rank FROM albums ORDER BY year_rank, title",
			true,
			"surface",
			["window-function", "dense-rank", "ordering"],
		),
		p(
			"pool-rank-artist-release-order",
			"Release order per artist",
			"For each album, return **artist_id**, **title**, and chronological position as **release_position**. Sort by artist and position.",
			"ROW_NUMBER partitioned by artist_id gives a unique sequence.",
			"SELECT artist_id, title, ROW_NUMBER() OVER (PARTITION BY artist_id ORDER BY release_year, id) AS release_position FROM albums ORDER BY artist_id, release_position",
			true,
			"surface",
			["window-function", "row-number", "partitioning", "ordering"],
		),
		p(
			"pool-rank-longest-track-each",
			"One longest track per album",
			"Return one longest track for each album. Show **album_id**, **title**, and **duration_seconds**, sorted by album id.",
			"Assign ROW_NUMBER by duration descending inside each album, then keep position 1.",
			"WITH ranked AS (SELECT album_id, title, duration_seconds, ROW_NUMBER() OVER (PARTITION BY album_id ORDER BY duration_seconds DESC, id) AS position FROM tracks) SELECT album_id, title, duration_seconds FROM ranked WHERE position = 1 ORDER BY album_id",
			true,
			"surface",
			["window-function", "row-number", "top-per-group", "cte"],
		),
		p(
			"pool-rank-top-three-buyers",
			"Top three buyers",
			"Return the three highest-spending customers. Show **name**, rounded **spend**, and **spend_rank**, preserving rank ties.",
			"Aggregate first, apply RANK second, and filter rank in an outer query.",
			"WITH spending AS (SELECT customers.name, SUM(albums.price * purchases.quantity) AS spend FROM customers JOIN purchases ON purchases.customer_id = customers.id JOIN albums ON albums.id = purchases.album_id GROUP BY customers.id, customers.name), ranked AS (SELECT name, spend, RANK() OVER (ORDER BY spend DESC) AS spend_rank FROM spending) SELECT name, ROUND(spend, 2) AS spend, spend_rank FROM ranked WHERE spend_rank <= 3 ORDER BY spend_rank, name",
			true,
			"surface",
			["window-function", "rank", "top-n", "grouping"],
		),
		p(
			"pool-rank-price-quartiles",
			"Price quartiles",
			"Assign every album to one of four price buckets. Return **title**, **price**, and **price_quartile**, with 1 as the most expensive bucket.",
			"NTILE(4) over descending price creates four near-equal groups.",
			"SELECT title, price, NTILE(4) OVER (ORDER BY price DESC, id) AS price_quartile FROM albums ORDER BY price_quartile, price DESC, title",
			true,
			"neighbour",
			["window-function", "ntile", "ordering"],
		),
		p(
			"pool-rank-customer-quantities",
			"Order size rank per customer",
			"For every purchase, return **customer_id**, **purchase_date**, **quantity**, and quantity rank within that customer as **quantity_rank**. Largest quantity is 1.",
			"PARTITION BY customer_id and rank quantity descending.",
			"SELECT customer_id, purchase_date, quantity, RANK() OVER (PARTITION BY customer_id ORDER BY quantity DESC) AS quantity_rank FROM purchases ORDER BY customer_id, quantity_rank, purchase_date",
			true,
			"neighbour",
			["window-function", "rank", "partitioning", "ordering"],
		),
		p(
			"pool-rank-cheapest-genre",
			"Cheapest album per genre",
			"Return every album tied for cheapest in its genre. Show **genre**, **title**, and **price**, sorted by genre and title.",
			"Use RANK ordered by price ascending inside each genre, then keep rank 1.",
			"WITH ranked AS (SELECT genre, title, price, RANK() OVER (PARTITION BY genre ORDER BY price) AS price_rank FROM albums) SELECT genre, title, price FROM ranked WHERE price_rank = 1 ORDER BY genre, title",
			true,
			"neighbour",
			["window-function", "rank", "top-per-group", "ties"],
		),
		p(
			"pool-rank-genres-by-average",
			"Rank genre price averages",
			"Return each **genre**, rounded **avg_price**, and **price_rank** from highest average to lowest.",
			"Aggregate by genre in a CTE, then rank the aggregate rows.",
			"WITH genre_prices AS (SELECT genre, AVG(price) AS avg_price FROM albums GROUP BY genre) SELECT genre, ROUND(avg_price, 2) AS avg_price, RANK() OVER (ORDER BY avg_price DESC) AS price_rank FROM genre_prices ORDER BY price_rank, genre",
			true,
			"trap",
			["window-function", "rank", "grouping", "query-stages"],
		),
		p(
			"pool-rank-purchase-sequence",
			"A single purchase timeline",
			"Number every purchase chronologically as **purchase_number**. Return **purchase_number**, **id**, and **purchase_date** in that order.",
			"ROW_NUMBER needs date and id as a deterministic tie-breaker.",
			"SELECT ROW_NUMBER() OVER (ORDER BY purchase_date, id) AS purchase_number, id, purchase_date FROM purchases ORDER BY purchase_number",
			true,
			"trap",
			["window-function", "row-number", "deterministic-order"],
		),
		p(
			"pool-rank-duration-ties",
			"Rank without losing rows",
			"Show all tracks with **title**, **duration_seconds**, and global **duration_rank**, longest first. Do not group equal durations together into one row.",
			"RANK calculates a value while preserving every input row. GROUP BY would change the grain.",
			"SELECT title, duration_seconds, RANK() OVER (ORDER BY duration_seconds DESC) AS duration_rank FROM tracks ORDER BY duration_rank, title",
			true,
			"trap",
			["window-function", "rank", "row-preservation", "ordering"],
		),
	],
};
