import { type AuthoredExercise, p } from "./practice-authoring";

export const nullHandlingPractice: Record<string, AuthoredExercise[]> = {
	"null-handling": [
		p(
			"pool-null-release-status",
			"Released or waiting",
			"Show every artist's **name** and `released` when they have at least one album, otherwise `no albums`, as **status**. Sort by name.",
			"LEFT JOIN, group at artist level, then test COUNT(albums.id) inside CASE.",
			"SELECT artists.name, CASE WHEN COUNT(albums.id) = 0 THEN 'no albums' ELSE 'released' END AS status FROM artists LEFT JOIN albums ON albums.artist_id = artists.id GROUP BY artists.id, artists.name ORDER BY artists.name",
			true,
			"surface",
			["null", "outer-join", "conditional"],
		),
		p(
			"pool-null-no-2023-sales",
			"No sales during 2023",
			"Return the **title** of each album with no purchase during 2023, alphabetically.",
			"Put the 2023 condition inside the LEFT JOIN. A WHERE date filter would remove the NULL rows you need.",
			"SELECT albums.title FROM albums LEFT JOIN purchases ON purchases.album_id = albums.id AND purchases.purchase_date >= '2023-01-01' AND purchases.purchase_date < '2024-01-01' WHERE purchases.id IS NULL ORDER BY albums.title",
			true,
			"surface",
			["null", "outer-join", "anti-join", "ordering"],
		),
		p(
			"pool-null-album-buyers",
			"Buyers per album, including zero",
			"For every album, return **title** and distinct buyer count as **buyer_count**. Keep never-purchased albums and sort by title.",
			"COUNT(DISTINCT purchases.customer_id) ignores the NULL produced by an unmatched LEFT JOIN.",
			"SELECT albums.title, COUNT(DISTINCT purchases.customer_id) AS buyer_count FROM albums LEFT JOIN purchases ON purchases.album_id = albums.id GROUP BY albums.id, albums.title ORDER BY albums.title",
			true,
			"surface",
			["null", "outer-join", "distinct", "grouping"],
		),
		p(
			"pool-null-zero-revenue",
			"Revenue with honest zeroes",
			"Show every album **title** and its **revenue**, including 0 for albums never purchased. Round revenue to 2 decimals and sort by title.",
			"SUM over no matching rows is NULL. Wrap the aggregate with COALESCE.",
			"SELECT albums.title, COALESCE(ROUND(SUM(albums.price * purchases.quantity), 2), 0) AS revenue FROM albums LEFT JOIN purchases ON purchases.album_id = albums.id GROUP BY albums.id, albums.title ORDER BY albums.title",
			true,
			"surface",
			["null", "outer-join", "coalesce", "grouping"],
		),
		p(
			"pool-null-never-sold-artists",
			"Artists with no sales",
			"Return artists whose catalog has never produced a purchase, including artists with no albums. Show **name** alphabetically.",
			"LEFT JOIN through albums to purchases, then keep artist groups with zero non-NULL purchase ids.",
			"SELECT artists.name FROM artists LEFT JOIN albums ON albums.artist_id = artists.id LEFT JOIN purchases ON purchases.album_id = albums.id GROUP BY artists.id, artists.name HAVING COUNT(purchases.id) = 0 ORDER BY artists.name",
			true,
			"neighbour",
			["null", "outer-join", "grouping-restrictions", "anti-join"],
		),
		p(
			"pool-null-total-units-by-artist",
			"Units for the whole roster",
			"Show every artist **name** and copies sold as **units**, using 0 when there were no purchases. Sort by units descending, then name.",
			"Preserve the artist first, then COALESCE the SUM rather than filtering missing rows away.",
			"SELECT artists.name, COALESCE(SUM(purchases.quantity), 0) AS units FROM artists LEFT JOIN albums ON albums.artist_id = artists.id LEFT JOIN purchases ON purchases.album_id = albums.id GROUP BY artists.id, artists.name ORDER BY units DESC, artists.name",
			true,
			"neighbour",
			["null", "outer-join", "coalesce", "multi-table"],
		),
		p(
			"pool-null-purchased-only",
			"Keep only matched albums",
			"Using a LEFT JOIN and an explicit NULL test, return every purchased album **title** once, alphabetically.",
			"IS NOT NULL keeps matched rows. DISTINCT removes repeat purchases of the same album.",
			"SELECT DISTINCT albums.title FROM albums LEFT JOIN purchases ON purchases.album_id = albums.id WHERE purchases.id IS NOT NULL ORDER BY albums.title",
			true,
			"neighbour",
			["null", "outer-join", "distinct", "ordering"],
		),
		p(
			"pool-null-count-row-trap",
			"Do not count the placeholder",
			"Show each artist **name** and album count as **album_count**, but only artists with zero or one album. Sort by name.",
			"After a LEFT JOIN, COUNT(*) is at least one for every artist. Count the nullable child id.",
			"SELECT artists.name, COUNT(albums.id) AS album_count FROM artists LEFT JOIN albums ON albums.artist_id = artists.id GROUP BY artists.id, artists.name HAVING COUNT(albums.id) <= 1 ORDER BY artists.name",
			true,
			"trap",
			["null", "outer-join", "count-semantics", "grouping-restrictions"],
		),
		p(
			"pool-null-no-album-id",
			"The missing foreign match",
			"Return the **name** and missing album id as **album_id** for artists without albums.",
			"The expected album_id is NULL. Do not replace or filter it.",
			"SELECT artists.name, albums.id AS album_id FROM artists LEFT JOIN albums ON albums.artist_id = artists.id WHERE albums.id IS NULL",
			false,
			"trap",
			["null", "outer-join", "projection"],
		),
		p(
			"pool-null-bulk-or-zero",
			"Bulk quantity or zero",
			"For each customer, total only quantities above 1 as **bulk_units**. Show 0 for customers with none and sort by name.",
			"A filtered SUM can be NULL when no row qualifies. COALESCE it after aggregation.",
			"SELECT customers.name, COALESCE(SUM(purchases.quantity) FILTER (WHERE purchases.quantity > 1), 0) AS bulk_units FROM customers LEFT JOIN purchases ON purchases.customer_id = customers.id GROUP BY customers.id, customers.name ORDER BY customers.name",
			true,
			"trap",
			["null", "filtered-aggregate", "coalesce", "outer-join"],
		),
	],
};
