import { type AuthoredExercise, p } from "./practice-authoring";

export const setOperationsPractice: Record<string, AuthoredExercise[]> = {
	"set-operations": [
		p(
			"pool-sets-people",
			"One people list",
			"Create one alphabetical **name** column from artist names and customer names, removing duplicates.",
			"Both SELECTs return one compatible text column. UNION handles deduplication.",
			"SELECT name FROM artists UNION SELECT name FROM customers ORDER BY name",
			true,
			"surface",
			["set-operation", "union", "ordering"],
		),
		p(
			"pool-sets-all-countries",
			"Country mentions, duplicates included",
			"Return every artist **country** and keep repeated countries. Sort alphabetically.",
			"Split the artists into two compatible SELECTs and combine with UNION ALL so the two USA rows survive.",
			"SELECT country FROM artists WHERE id <= 4 UNION ALL SELECT country FROM artists WHERE id > 4 ORDER BY country",
			true,
			"surface",
			["set-operation", "union-all", "duplicates", "ordering"],
		),
		p(
			"pool-sets-common-ids",
			"IDs shared by people tables",
			"Return **id** values present in both artists and customers, lowest first.",
			"INTERSECT returns only values that appear on both sides.",
			"SELECT id FROM artists INTERSECT SELECT id FROM customers ORDER BY id",
			true,
			"surface",
			["set-operation", "intersection", "ordering"],
		),
		p(
			"pool-sets-not-sold-2023",
			"Catalog minus 2023 sales",
			"Without a JOIN or subquery, return album **id** values with no purchase during 2023.",
			"Start with all album ids, then EXCEPT album ids from purchases dated in 2023.",
			"SELECT id FROM albums EXCEPT SELECT album_id FROM purchases WHERE purchase_date >= '2023-01-01' AND purchase_date < '2024-01-01' ORDER BY id",
			true,
			"surface",
			["set-operation", "difference", "anti-join", "ordering"],
		),
		p(
			"pool-sets-shared-years",
			"Years in the roster and catalog",
			"List years that are both an artist formation year and an album release year, newest first.",
			"This is an intersection, followed by descending compound-result order.",
			"SELECT formed_year AS year FROM artists INTERSECT SELECT release_year FROM albums ORDER BY year DESC",
			true,
			"neighbour",
			["set-operation", "intersection", "ordering"],
		),
		p(
			"pool-sets-release-only-years",
			"Catalog-only years",
			"Return album release **year** values that are not artist formation years, earliest first.",
			"Put release years on the left of EXCEPT and formation years on the right.",
			"SELECT release_year AS year FROM albums EXCEPT SELECT formed_year FROM artists ORDER BY year",
			true,
			"neighbour",
			["set-operation", "difference", "ordering"],
		),
		p(
			"pool-sets-premium-purchased-genres",
			"Premium and purchased genres",
			"List **genre** values that have an album priced at 15 or more and also had a purchase, alphabetically.",
			"Build each genre set independently, then INTERSECT them.",
			"SELECT genre FROM albums WHERE price >= 15 INTERSECT SELECT albums.genre FROM albums JOIN purchases ON purchases.album_id = albums.id ORDER BY genre",
			true,
			"neighbour",
			["set-operation", "intersection", "multi-table", "restriction"],
		),
		p(
			"pool-sets-source-label",
			"A typed directory",
			"Build one list with **name** and **kind**. Artists use `artist`; customers use `customer`. Sort by kind then name.",
			"Both branches need two columns in the same order and compatible types.",
			"SELECT name, 'artist' AS kind FROM artists UNION ALL SELECT name, 'customer' AS kind FROM customers ORDER BY kind, name",
			true,
			"trap",
			["set-operation", "union-all", "column-compatibility", "ordering"],
		),
		p(
			"pool-sets-country-dedup-trap",
			"One row per country",
			"Combine countries from artists with cities from customers as **place**, returning each text value once.",
			"The request says once. UNION ALL would preserve duplicate USA and Cairo values.",
			"SELECT country AS place FROM artists UNION SELECT city FROM customers",
			false,
			"trap",
			["set-operation", "union", "duplicates"],
		),
		p(
			"pool-sets-union-all-count",
			"Count every source row",
			"Count how many rows result when every artist country and every customer city are stacked without deduplication. Name it **row_count**.",
			"UNION ALL belongs inside a derived table. COUNT its rows outside.",
			"SELECT COUNT(*) AS row_count FROM (SELECT country AS place FROM artists UNION ALL SELECT city FROM customers)",
			false,
			"trap",
			["set-operation", "union-all", "derived-table", "aggregate-function"],
		),
	],
};
