import { type AuthoredExercise, p } from "./practice-authoring";

export const correlatedSubqueriesPractice: Record<string, AuthoredExercise[]> =
	{
		"correlated-subqueries": [
			p(
				"pool-corr-above-genre-average",
				"Above the genre average",
				"Return albums priced above the average for their own genre. Show **title**, **genre**, and **price**, highest first.",
				"Correlate the inner AVG on outer_album.genre.",
				"SELECT outer_album.title, outer_album.genre, outer_album.price FROM albums AS outer_album WHERE outer_album.price > (SELECT AVG(inner_album.price) FROM albums AS inner_album WHERE inner_album.genre = outer_album.genre) ORDER BY outer_album.price DESC, outer_album.title",
				true,
				"surface",
				["correlated-subquery", "aggregate-vs-column-value", "ordering"],
			),
			p(
				"pool-corr-below-album-average",
				"Shorter than their album",
				"Return tracks shorter than the average duration on their own album. Show **title** and **duration_seconds**, shortest first.",
				"The inner AVG must use the current outer track's album_id.",
				"SELECT outer_track.title, outer_track.duration_seconds FROM tracks AS outer_track WHERE outer_track.duration_seconds < (SELECT AVG(inner_track.duration_seconds) FROM tracks AS inner_track WHERE inner_track.album_id = outer_track.album_id) ORDER BY outer_track.duration_seconds, outer_track.title",
				true,
				"surface",
				["correlated-subquery", "aggregate-vs-column-value", "ordering"],
			),
			p(
				"pool-corr-latest-albums",
				"Latest release per artist",
				"Return each artist's latest album or albums if tied. Show artist **name**, album **title**, and **release_year**, sorted by artist.",
				"Compare each album year to MAX(release_year) for its artist_id.",
				"SELECT artists.name, outer_album.title, outer_album.release_year FROM albums AS outer_album JOIN artists ON artists.id = outer_album.artist_id WHERE outer_album.release_year = (SELECT MAX(inner_album.release_year) FROM albums AS inner_album WHERE inner_album.artist_id = outer_album.artist_id) ORDER BY artists.name, outer_album.title",
				true,
				"surface",
				["correlated-subquery", "aggregate-vs-column-value", "multi-table"],
			),
			p(
				"pool-corr-world-customers",
				"At least one World purchase",
				"Using EXISTS, return customer **name** values for people who bought a World album, alphabetically.",
				"The inner query joins purchases to albums and correlates customer_id to the outer customer.",
				"SELECT customers.name FROM customers WHERE EXISTS (SELECT 1 FROM purchases JOIN albums ON albums.id = purchases.album_id WHERE purchases.customer_id = customers.id AND albums.genre = 'World') ORDER BY customers.name",
				true,
				"surface",
				["correlated-subquery", "exists", "multi-table", "ordering"],
			),
			p(
				"pool-corr-no-cairo-sales",
				"Never bought from Cairo",
				"Using NOT EXISTS, return album **title** values never purchased by a customer in Cairo, alphabetically.",
				"The nested query joins purchases to customers, correlates album_id, and looks specifically for Cairo.",
				"SELECT albums.title FROM albums WHERE NOT EXISTS (SELECT 1 FROM purchases JOIN customers ON customers.id = purchases.customer_id WHERE purchases.album_id = albums.id AND customers.city = 'Cairo') ORDER BY albums.title",
				true,
				"neighbour",
				["correlated-subquery", "does-not-exist", "anti-join", "ordering"],
			),
			p(
				"pool-corr-only-single-copies",
				"Never ordered in bulk",
				"Return customers who purchased at least once but never ordered more than one copy at a time. Show **name** alphabetically.",
				"Require one purchase with EXISTS, and reject any quantity above 1 with NOT EXISTS.",
				"SELECT customers.name FROM customers WHERE EXISTS (SELECT 1 FROM purchases WHERE purchases.customer_id = customers.id) AND NOT EXISTS (SELECT 1 FROM purchases WHERE purchases.customer_id = customers.id AND purchases.quantity > 1) ORDER BY customers.name",
				true,
				"neighbour",
				["correlated-subquery", "exists", "does-not-exist", "conjunction"],
			),
			p(
				"pool-corr-prolific-artists",
				"Count from the outer row",
				"Using a correlated scalar subquery, return artist **name** values for artists with at least two albums, alphabetically.",
				"The nested COUNT should compare albums.artist_id to artists.id.",
				"SELECT artists.name FROM artists WHERE (SELECT COUNT(*) FROM albums WHERE albums.artist_id = artists.id) >= 2 ORDER BY artists.name",
				true,
				"neighbour",
				[
					"correlated-subquery",
					"aggregate-function",
					"restriction",
					"ordering",
				],
			),
			p(
				"pool-corr-priciest-by-genre",
				"Priciest in every genre",
				"Return every album tied for highest price in its genre. Show **genre**, **title**, and **price**, sorted by genre and title.",
				"Use equality to the correlated MAX so ties are preserved.",
				"SELECT outer_album.genre, outer_album.title, outer_album.price FROM albums AS outer_album WHERE outer_album.price = (SELECT MAX(inner_album.price) FROM albums AS inner_album WHERE inner_album.genre = outer_album.genre) ORDER BY outer_album.genre, outer_album.title",
				true,
				"trap",
				[
					"correlated-subquery",
					"ties",
					"aggregate-vs-column-value",
					"ordering",
				],
			),
			p(
				"pool-corr-first-purchases",
				"Each customer's first purchase",
				"Return every customer's first purchase row, keeping same-day ties. Show **customer_id**, **album_id**, and **purchase_date**, sorted by customer and album.",
				"Compare each row's date to the correlated MIN date. LIMIT 1 would lose ties and work globally.",
				"SELECT outer_purchase.customer_id, outer_purchase.album_id, outer_purchase.purchase_date FROM purchases AS outer_purchase WHERE outer_purchase.purchase_date = (SELECT MIN(inner_purchase.purchase_date) FROM purchases AS inner_purchase WHERE inner_purchase.customer_id = outer_purchase.customer_id) ORDER BY outer_purchase.customer_id, outer_purchase.album_id",
				true,
				"trap",
				[
					"correlated-subquery",
					"ties",
					"aggregate-vs-column-value",
					"ordering",
				],
			),
			p(
				"pool-corr-above-own-order-average",
				"Larger than their usual order",
				"Return purchases whose **quantity** is above that customer's own average. Show **customer_id**, **purchase_date**, and **quantity**, sorted by customer and date.",
				"A global AVG answers a different question. Correlate the average by customer_id.",
				"SELECT outer_purchase.customer_id, outer_purchase.purchase_date, outer_purchase.quantity FROM purchases AS outer_purchase WHERE outer_purchase.quantity > (SELECT AVG(inner_purchase.quantity) FROM purchases AS inner_purchase WHERE inner_purchase.customer_id = outer_purchase.customer_id) ORDER BY outer_purchase.customer_id, outer_purchase.purchase_date",
				true,
				"trap",
				[
					"correlated-subquery",
					"aggregate-vs-column-value",
					"metric-grain",
					"ordering",
				],
			),
		],
	};
