import { type AuthoredExercise, p } from "./practice-authoring";

export const advancedAggregationPractice: Record<string, AuthoredExercise[]> = {
	"advanced-aggregation": [
		p(
			"pool-agg-orders-vs-units",
			"Orders and units by year",
			"For each purchase **year**, show order count as **orders** and total quantity as **units**, earliest year first.",
			"COUNT rows for orders and SUM quantity for units. They are intentionally different metrics.",
			"SELECT strftime('%Y', purchase_date) AS year, COUNT(*) AS orders, SUM(quantity) AS units FROM purchases GROUP BY year ORDER BY year",
			true,
			"surface",
			["grouping", "aggregate-function", "metric-grain", "dates"],
		),
		p(
			"pool-agg-customer-order-size",
			"Average order size",
			"For each purchasing customer, return **name** and average quantity per purchase as **avg_quantity**, rounded to 2 decimals. Sort by name.",
			"Group at customer grain and average the purchase quantity column.",
			"SELECT customers.name, ROUND(AVG(purchases.quantity), 2) AS avg_quantity FROM customers JOIN purchases ON purchases.customer_id = customers.id GROUP BY customers.id, customers.name ORDER BY customers.name",
			true,
			"surface",
			["grouping", "aggregate-function", "multi-table", "ordering"],
		),
		p(
			"pool-agg-genre-duration",
			"Average track length by genre",
			"For each genre with tracks, show **genre** and average track seconds as **avg_seconds**, rounded to 1 decimal. Longest average first.",
			"Join albums to tracks, then aggregate at genre grain.",
			"SELECT albums.genre, ROUND(AVG(tracks.duration_seconds), 1) AS avg_seconds FROM albums JOIN tracks ON tracks.album_id = albums.id GROUP BY albums.genre ORDER BY avg_seconds DESC, albums.genre",
			true,
			"surface",
			["grouping", "aggregate-function", "multi-table", "ordering"],
		),
		p(
			"pool-agg-artist-era-counts",
			"Catalog before and after 2010",
			"For each artist with albums, return **name**, count before 2010 as **older**, and count from 2010 onward as **newer**. Sort by name.",
			"Use two filtered counts inside one artist-level aggregation.",
			"SELECT artists.name, COUNT(*) FILTER (WHERE albums.release_year < 2010) AS older, COUNT(*) FILTER (WHERE albums.release_year >= 2010) AS newer FROM artists JOIN albums ON albums.artist_id = artists.id GROUP BY artists.id, artists.name ORDER BY artists.name",
			true,
			"surface",
			["grouping", "filtered-aggregate", "multi-table", "ordering"],
		),
		p(
			"pool-agg-genre-catalog-share",
			"Share of the catalog",
			"For each genre, show **genre** and its percentage of all albums as **catalog_pct**, rounded to 1 decimal. Sort largest first.",
			"Divide the grouped COUNT by a scalar total. Use 100.0 to keep decimal division.",
			"SELECT genre, ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM albums), 1) AS catalog_pct FROM albums GROUP BY genre ORDER BY catalog_pct DESC, genre",
			true,
			"neighbour",
			["grouping", "ratio", "scalar-subquery", "numeric-types"],
		),
		p(
			"pool-agg-weighted-price",
			"Average selling price per copy",
			"Calculate the quantity-weighted album price across all purchases as **avg_selling_price**, rounded to 2 decimals.",
			"Total revenue divided by total units is weighted. AVG(price) would weight every purchase row equally.",
			"SELECT ROUND(SUM(albums.price * purchases.quantity) / SUM(purchases.quantity), 2) AS avg_selling_price FROM purchases JOIN albums ON albums.id = purchases.album_id",
			false,
			"neighbour",
			[
				"aggregate-function",
				"weighted-average",
				"multi-table",
				"numeric-types",
			],
		),
		p(
			"pool-agg-customer-span",
			"First to latest purchase",
			"For customers with at least two purchases, return **name**, first date as **first_purchase**, and last date as **latest_purchase**. Sort by name.",
			"MIN and MAX dates work because they use YYYY-MM-DD text. Filter groups with HAVING.",
			"SELECT customers.name, MIN(purchases.purchase_date) AS first_purchase, MAX(purchases.purchase_date) AS latest_purchase FROM customers JOIN purchases ON purchases.customer_id = customers.id GROUP BY customers.id, customers.name HAVING COUNT(*) >= 2 ORDER BY customers.name",
			true,
			"neighbour",
			["grouping", "aggregate-function", "grouping-restrictions", "dates"],
		),
		p(
			"pool-agg-genre-buyers",
			"Distinct buyers by genre",
			"For each purchased genre, return **genre** and unique customer count as **buyers**, most buyers first.",
			"A customer can buy more than one album in a genre. Count distinct customer_id.",
			"SELECT albums.genre, COUNT(DISTINCT purchases.customer_id) AS buyers FROM purchases JOIN albums ON albums.id = purchases.album_id GROUP BY albums.genre ORDER BY buyers DESC, albums.genre",
			true,
			"trap",
			["grouping", "distinct", "multi-table", "duplicates"],
		),
		p(
			"pool-agg-busy-expensive-genres",
			"Volume and value together",
			"Return genres with at least two albums and average price above 12. Show **genre**, **album_count**, and rounded **avg_price**.",
			"Both conditions describe whole groups, so both belong in HAVING.",
			"SELECT genre, COUNT(*) AS album_count, ROUND(AVG(price), 2) AS avg_price FROM albums GROUP BY genre HAVING COUNT(*) >= 2 AND AVG(price) > 12 ORDER BY genre",
			true,
			"trap",
			[
				"grouping",
				"grouping-restrictions",
				"aggregate-function",
				"conjunction",
			],
		),
		p(
			"pool-agg-no-inflated-revenue",
			"Revenue at the right grain",
			"Return total shop **revenue**, rounded to 2 decimals. Each purchase contributes album price times its quantity.",
			"Do not join tracks. That would repeat each album sale once per track and inflate the result.",
			"SELECT ROUND(SUM(albums.price * purchases.quantity), 2) AS revenue FROM purchases JOIN albums ON albums.id = purchases.album_id",
			false,
			"trap",
			["aggregate-function", "metric-grain", "multi-table"],
		),
	],

	ctes: [
		p(
			"pool-cte-long-tracks",
			"Name the long tracks",
			"Use a CTE named `long_tracks` for tracks at least 270 seconds. Return **title** and **duration_seconds**, longest first.",
			"The outer query should read from the CTE, not repeat its filter.",
			"WITH long_tracks AS (SELECT title, duration_seconds FROM tracks WHERE duration_seconds >= 270) SELECT title, duration_seconds FROM long_tracks ORDER BY duration_seconds DESC, title",
			true,
			"surface",
			["cte", "restriction", "ordering"],
		),
		p(
			"pool-cte-track-counts",
			"Track counts with album titles",
			"Use a CTE to count tracks per album_id, then return album **title** and **track_count** for albums with at least two tracks. Sort by title.",
			"Aggregate tracks first, then join the compact result to albums.",
			"WITH track_counts AS (SELECT album_id, COUNT(*) AS track_count FROM tracks GROUP BY album_id) SELECT albums.title, track_counts.track_count FROM track_counts JOIN albums ON albums.id = track_counts.album_id WHERE track_counts.track_count >= 2 ORDER BY albums.title",
			true,
			"surface",
			["cte", "grouping", "multi-table", "ordering"],
		),
		p(
			"pool-cte-customer-revenue",
			"Customer revenue stage",
			"Build customer spend in a CTE, then return **name** and rounded **spend** for totals above 25. Sort highest first.",
			"The threshold applies to the aggregated CTE column in the outer query.",
			"WITH customer_spend AS (SELECT customers.id, customers.name, SUM(albums.price * purchases.quantity) AS spend FROM customers JOIN purchases ON purchases.customer_id = customers.id JOIN albums ON albums.id = purchases.album_id GROUP BY customers.id, customers.name) SELECT name, ROUND(spend, 2) AS spend FROM customer_spend WHERE spend > 25 ORDER BY spend DESC, name",
			true,
			"surface",
			["cte", "grouping", "multi-table", "restriction"],
		),
		p(
			"pool-cte-recursive-numbers",
			"Track positions one through three",
			"Use a recursive CTE to generate **track_number** values 1, 2, and 3 in order.",
			"Seed with 1, add 1 recursively, and stop before the value can exceed 3.",
			"WITH RECURSIVE positions(track_number) AS (VALUES(1) UNION ALL SELECT track_number + 1 FROM positions WHERE track_number < 3) SELECT track_number FROM positions ORDER BY track_number",
			true,
			"surface",
			["cte", "recursion", "sequence"],
		),
		p(
			"pool-cte-above-catalog-average",
			"Name the catalog average",
			"Use one CTE for the average album price, then show titles and prices above it, highest first.",
			"A one-row CTE can be joined without a key using CROSS JOIN.",
			"WITH catalog_average AS (SELECT AVG(price) AS avg_price FROM albums) SELECT albums.title, albums.price FROM albums CROSS JOIN catalog_average WHERE albums.price > catalog_average.avg_price ORDER BY albums.price DESC, albums.title",
			true,
			"neighbour",
			["cte", "aggregate-function", "cross-join", "restriction"],
		),
		p(
			"pool-cte-two-aggregates",
			"Orders and spend in stages",
			"Using separate CTEs for order counts and spend, return customer **name**, **orders**, and rounded **spend**. Sort by name.",
			"Aggregate each metric by customer_id, then join both CTEs to customers.",
			"WITH order_counts AS (SELECT customer_id, COUNT(*) AS orders FROM purchases GROUP BY customer_id), spending AS (SELECT purchases.customer_id, SUM(albums.price * purchases.quantity) AS spend FROM purchases JOIN albums ON albums.id = purchases.album_id GROUP BY purchases.customer_id) SELECT customers.name, order_counts.orders, ROUND(spending.spend, 2) AS spend FROM customers JOIN order_counts ON order_counts.customer_id = customers.id JOIN spending ON spending.customer_id = customers.id ORDER BY customers.name",
			true,
			"neighbour",
			["cte", "multiple-ctes", "grouping", "multi-table"],
		),
		p(
			"pool-cte-best-months",
			"Busiest purchase months",
			"Aggregate purchase counts by month in a CTE, then return every tied busiest **month** and **purchase_count**.",
			"Compare the CTE's count to a scalar MAX taken from the same CTE.",
			"WITH monthly AS (SELECT strftime('%Y-%m', purchase_date) AS month, COUNT(*) AS purchase_count FROM purchases GROUP BY month) SELECT month, purchase_count FROM monthly WHERE purchase_count = (SELECT MAX(purchase_count) FROM monthly) ORDER BY month",
			true,
			"neighbour",
			["cte", "grouping", "scalar-subquery", "ties"],
		),
		p(
			"pool-cte-one-definition",
			"Define it once",
			"Use one CTE named `rock_albums` and return its cheapest and most expensive prices as **min_price** and **max_price**.",
			"Filter Rock albums inside the CTE. The outer query should aggregate that named result.",
			"WITH rock_albums AS (SELECT price FROM albums WHERE genre = 'Rock') SELECT MIN(price) AS min_price, MAX(price) AS max_price FROM rock_albums",
			false,
			"trap",
			["cte", "aggregate-function", "restriction"],
		),
		p(
			"pool-cte-preserve-zeroes",
			"CTE counts, including zero",
			"Create album counts by artist in a CTE, then show every artist **name** and **album_count**, using 0 when no CTE row matches.",
			"Start from artists, LEFT JOIN the CTE, and COALESCE its missing count.",
			"WITH album_counts AS (SELECT artist_id, COUNT(*) AS album_count FROM albums GROUP BY artist_id) SELECT artists.name, COALESCE(album_counts.album_count, 0) AS album_count FROM artists LEFT JOIN album_counts ON album_counts.artist_id = artists.id ORDER BY artists.name",
			true,
			"trap",
			["cte", "outer-join", "coalesce", "grouping"],
		),
		p(
			"pool-cte-calendar",
			"A complete sales calendar",
			"Generate years 2021 through 2024 recursively and show each **year** with total **units**, including 0 if a year has none.",
			"LEFT JOIN the generated years to purchases and COALESCE the SUM.",
			"WITH RECURSIVE years(year) AS (VALUES(2021) UNION ALL SELECT year + 1 FROM years WHERE year < 2024) SELECT years.year, COALESCE(SUM(purchases.quantity), 0) AS units FROM years LEFT JOIN purchases ON CAST(strftime('%Y', purchases.purchase_date) AS INTEGER) = years.year GROUP BY years.year ORDER BY years.year",
			true,
			"trap",
			["cte", "recursion", "outer-join", "coalesce"],
		),
	],
};
