import { type AuthoredExercise, p } from "./practice-authoring";

export const windowAnalyticsPractice: Record<string, AuthoredExercise[]> = {
	"window-analytics": [
		p(
			"pool-window-running-revenue",
			"Running revenue",
			"For each purchase, show **id**, **purchase_date**, and cumulative revenue as **running_revenue**, rounded to 2 decimals in date order.",
			"Join price onto each purchase, then use ordered SUM(price * quantity).",
			"SELECT purchases.id, purchases.purchase_date, ROUND(SUM(albums.price * purchases.quantity) OVER (ORDER BY purchases.purchase_date, purchases.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW), 2) AS running_revenue FROM purchases JOIN albums ON albums.id = purchases.album_id ORDER BY purchases.purchase_date, purchases.id",
			true,
			"surface",
			["window-function", "running-total", "multi-table", "ordering"],
		),
		p(
			"pool-window-customer-running-units",
			"Running units per customer",
			"Show **customer_id**, **purchase_date**, **quantity**, and that customer's cumulative quantity as **customer_units**.",
			"PARTITION BY customer_id makes each running total restart.",
			"SELECT customer_id, purchase_date, quantity, SUM(quantity) OVER (PARTITION BY customer_id ORDER BY purchase_date, id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS customer_units FROM purchases ORDER BY customer_id, purchase_date, id",
			true,
			"surface",
			["window-function", "running-total", "partitioning", "ordering"],
		),
		p(
			"pool-window-quantity-change",
			"Change from the prior order",
			"For each purchase, return **customer_id**, **purchase_date**, and quantity change from that customer's prior purchase as **quantity_change**. The first can be NULL.",
			"Subtract LAG(quantity) partitioned by customer from the current quantity.",
			"SELECT customer_id, purchase_date, quantity - LAG(quantity) OVER (PARTITION BY customer_id ORDER BY purchase_date, id) AS quantity_change FROM purchases ORDER BY customer_id, purchase_date, id",
			true,
			"surface",
			["window-function", "lag", "partitioning", "expressions"],
		),
		p(
			"pool-window-next-release-gap",
			"Years until the next album",
			"For each album that has a later release by the same artist, return **title** and years until it as **years_to_next**. Sort by artist and release year.",
			"Use LEAD(release_year) by artist in a CTE, then remove rows where the next year is NULL.",
			"WITH timeline AS (SELECT artist_id, title, release_year, LEAD(release_year) OVER (PARTITION BY artist_id ORDER BY release_year, id) AS next_year FROM albums) SELECT title, next_year - release_year AS years_to_next FROM timeline WHERE next_year IS NOT NULL ORDER BY artist_id, release_year",
			true,
			"surface",
			["window-function", "lead", "partitioning", "cte"],
		),
		p(
			"pool-window-priciest-title",
			"Show each artist's priciest title",
			"For every album row, show **artist_id**, **title**, and that artist's highest-priced album title as **priciest_title**. Sort by artist and title.",
			"FIRST_VALUE(title) over price descending returns the leader without collapsing rows.",
			"SELECT artist_id, title, FIRST_VALUE(title) OVER (PARTITION BY artist_id ORDER BY price DESC, id) AS priciest_title FROM albums ORDER BY artist_id, title",
			true,
			"neighbour",
			["window-function", "first-value", "partitioning", "row-preservation"],
		),
		p(
			"pool-window-track-moving-average",
			"Moving track average",
			"Show **album_id**, **track_number**, and average duration of the current and previous track as **moving_avg**, rounded to 1 decimal.",
			"Use a one-row preceding frame within each album.",
			"SELECT album_id, track_number, ROUND(AVG(duration_seconds) OVER (PARTITION BY album_id ORDER BY track_number ROWS BETWEEN 1 PRECEDING AND CURRENT ROW), 1) AS moving_avg FROM tracks ORDER BY album_id, track_number",
			true,
			"neighbour",
			["window-function", "moving-average", "window-frame", "partitioning"],
		),
		p(
			"pool-window-unit-share",
			"Each order's unit share",
			"For every purchase, return **id**, **quantity**, and percent of all units as **unit_pct**, rounded to 1 decimal. Sort by id.",
			"SUM(quantity) OVER () supplies the total while preserving each purchase row.",
			"SELECT id, quantity, ROUND(100.0 * quantity / SUM(quantity) OVER (), 1) AS unit_pct FROM purchases ORDER BY id",
			true,
			"neighbour",
			["window-function", "ratio", "row-preservation", "numeric-types"],
		),
		p(
			"pool-window-cumulative-customer-share",
			"Cumulative customer revenue share",
			"Order customers by spend and return **name**, **spend**, and cumulative percent of revenue as **cumulative_pct**, rounded to 2 decimals.",
			"Aggregate customer spend first. The numerator is an ordered running SUM and the denominator is SUM over all rows.",
			"WITH spending AS (SELECT customers.name, SUM(albums.price * purchases.quantity) AS spend FROM customers JOIN purchases ON purchases.customer_id = customers.id JOIN albums ON albums.id = purchases.album_id GROUP BY customers.id, customers.name) SELECT name, ROUND(spend, 2) AS spend, ROUND(100.0 * SUM(spend) OVER (ORDER BY spend DESC, name ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(spend) OVER (), 2) AS cumulative_pct FROM spending ORDER BY spend DESC, name",
			true,
			"trap",
			["window-function", "running-total", "ratio", "grouping"],
		),
		p(
			"pool-window-vs-customer-average",
			"Order size versus personal average",
			"For each purchase, show **customer_id**, **quantity**, and difference from that customer's average as **from_average**, rounded to 1 decimal.",
			"Subtract a partitioned window AVG, not a grouped AVG that removes individual purchases.",
			"SELECT customer_id, quantity, ROUND(quantity - AVG(quantity) OVER (PARTITION BY customer_id), 1) AS from_average FROM purchases ORDER BY customer_id, id",
			true,
			"trap",
			[
				"window-function",
				"partitioning",
				"row-preservation",
				"aggregate-vs-column-value",
			],
		),
		p(
			"pool-window-repeat-count",
			"Customer purchase count on every row",
			"Keep every purchase row and add that customer's number of purchases as **customer_purchase_count**. Return **id**, **customer_id**, and the count.",
			"COUNT(*) OVER (PARTITION BY customer_id) annotates rows. GROUP BY would return one row per customer.",
			"SELECT id, customer_id, COUNT(*) OVER (PARTITION BY customer_id) AS customer_purchase_count FROM purchases ORDER BY id",
			true,
			"trap",
			[
				"window-function",
				"partitioning",
				"row-preservation",
				"count-semantics",
			],
		),
	],
};
