import { type AuthoredExercise, p } from "./practice-authoring";

export const businessAnalyticsPractice: Record<string, AuthoredExercise[]> = {
	"business-analytics": [
		p(
			"pool-biz-repeat-customers",
			"Repeat customers",
			"Return customers with at least two purchases. Show **name** and order count as **orders**, most orders first.",
			"Aggregate at customer grain and apply the threshold with HAVING.",
			"SELECT customers.name, COUNT(*) AS orders FROM customers JOIN purchases ON purchases.customer_id = customers.id GROUP BY customers.id, customers.name HAVING COUNT(*) >= 2 ORDER BY orders DESC, customers.name",
			true,
			"surface",
			["business-metric", "grouping", "grouping-restrictions", "multi-table"],
		),
		p(
			"pool-biz-average-order-value",
			"Average order value",
			"Calculate the average revenue per purchase as **avg_order_value**, rounded to 2 decimals.",
			"Each purchase row's value is price times quantity. Average those row values.",
			"SELECT ROUND(AVG(albums.price * purchases.quantity), 2) AS avg_order_value FROM purchases JOIN albums ON albums.id = purchases.album_id",
			false,
			"surface",
			["business-metric", "aggregate-function", "multi-table", "metric-grain"],
		),
		p(
			"pool-biz-dormant-inventory",
			"Inventory with no recent sale",
			"Return albums with no purchase in 2023 or later. Show **title**, **genre**, and **price**, highest price first.",
			"Use NOT EXISTS at album grain and apply the date boundary inside the correlated subquery.",
			"SELECT albums.title, albums.genre, albums.price FROM albums WHERE NOT EXISTS (SELECT 1 FROM purchases WHERE purchases.album_id = albums.id AND purchases.purchase_date >= '2023-01-01') ORDER BY albums.price DESC, albums.title",
			true,
			"surface",
			["business-metric", "anti-join", "correlated-subquery", "ordering"],
		),
		p(
			"pool-biz-yearly-top-customer",
			"Top customer each year",
			"Return the highest-spending customer or customers in each purchase year. Show **year**, **name**, and rounded **spend**, sorted by year and name.",
			"Aggregate customer-year spend, rank within year, and keep rank 1.",
			"WITH customer_year AS (SELECT CAST(strftime('%Y', purchases.purchase_date) AS INTEGER) AS year, customers.name, SUM(albums.price * purchases.quantity) AS spend FROM purchases JOIN customers ON customers.id = purchases.customer_id JOIN albums ON albums.id = purchases.album_id GROUP BY year, customers.id, customers.name), ranked AS (SELECT year, name, spend, RANK() OVER (PARTITION BY year ORDER BY spend DESC) AS position FROM customer_year) SELECT year, name, ROUND(spend, 2) AS spend FROM ranked WHERE position = 1 ORDER BY year, name",
			true,
			"surface",
			["business-metric", "grouping", "window-function", "top-per-group"],
		),
		p(
			"pool-biz-monthly-revenue",
			"Monthly revenue trend",
			"Return each purchase **month** in `YYYY-MM` form and rounded **revenue**, earliest first.",
			"Group price times quantity by the extracted month.",
			"SELECT strftime('%Y-%m', purchases.purchase_date) AS month, ROUND(SUM(albums.price * purchases.quantity), 2) AS revenue FROM purchases JOIN albums ON albums.id = purchases.album_id GROUP BY month ORDER BY month",
			true,
			"neighbour",
			["business-metric", "dates", "grouping", "multi-table"],
		),
		p(
			"pool-biz-genre-reach",
			"Genre volume and reach",
			"For each purchased genre, show total **units** and distinct **buyers**. Sort by units descending, then genre.",
			"SUM quantity measures volume. COUNT(DISTINCT customer_id) measures reach.",
			"SELECT albums.genre, SUM(purchases.quantity) AS units, COUNT(DISTINCT purchases.customer_id) AS buyers FROM purchases JOIN albums ON albums.id = purchases.album_id GROUP BY albums.genre ORDER BY units DESC, albums.genre",
			true,
			"neighbour",
			["business-metric", "grouping", "distinct", "metric-grain"],
		),
		p(
			"pool-biz-basket-pairs",
			"Same-day basket pairs",
			"Find album pairs bought by one customer on the same day. Return customer **name**, first album as **album_one**, and second as **album_two** once per pair.",
			"Self join purchases on customer and date, keep first.album_id < second.album_id, then join album names twice.",
			"SELECT customers.name, first_album.title AS album_one, second_album.title AS album_two FROM purchases AS first_purchase JOIN purchases AS second_purchase ON first_purchase.customer_id = second_purchase.customer_id AND first_purchase.purchase_date = second_purchase.purchase_date AND first_purchase.album_id < second_purchase.album_id JOIN customers ON customers.id = first_purchase.customer_id JOIN albums AS first_album ON first_album.id = first_purchase.album_id JOIN albums AS second_album ON second_album.id = second_purchase.album_id ORDER BY customers.name, album_one, album_two",
			true,
			"neighbour",
			["business-metric", "self-join", "multi-table", "pairs"],
		),
		p(
			"pool-biz-favorite-genres",
			"Each customer's favorite genre",
			"Return every customer's most-purchased genre by units, keeping ties. Show **name**, **genre**, and **units**, sorted by name and genre.",
			"Aggregate customer-genre units, rank within customer, then keep rank 1.",
			"WITH preferences AS (SELECT customers.id AS customer_id, customers.name, albums.genre, SUM(purchases.quantity) AS units FROM purchases JOIN customers ON customers.id = purchases.customer_id JOIN albums ON albums.id = purchases.album_id GROUP BY customers.id, customers.name, albums.genre), ranked AS (SELECT name, genre, units, RANK() OVER (PARTITION BY customer_id ORDER BY units DESC) AS position FROM preferences) SELECT name, genre, units FROM ranked WHERE position = 1 ORDER BY name, genre",
			true,
			"trap",
			["business-metric", "grouping", "window-function", "ties"],
		),
		p(
			"pool-biz-artist-scorecard",
			"Artist scorecard with zeroes",
			"Show every artist **name**, catalog size as **albums**, and copies sold as **units**, including zeroes. Sort by units descending, then name.",
			"Two one-to-many joins can multiply album rows. Count distinct albums and sum purchase quantities at the preserved artist grain.",
			"SELECT artists.name, COUNT(DISTINCT albums.id) AS albums, COALESCE(SUM(purchases.quantity), 0) AS units FROM artists LEFT JOIN albums ON albums.artist_id = artists.id LEFT JOIN purchases ON purchases.album_id = albums.id GROUP BY artists.id, artists.name ORDER BY units DESC, artists.name",
			true,
			"trap",
			["business-metric", "outer-join", "distinct", "metric-grain"],
		),
		p(
			"pool-biz-cumulative-buyers",
			"How quickly top buyers add up",
			"Order customers by spend and show **name**, rounded **spend**, and cumulative revenue percentage as **cumulative_pct**. Sort highest spend first.",
			"Aggregate first. Divide the running spend total by the full spend total, both as windows over customer rows.",
			"WITH spending AS (SELECT customers.name, SUM(albums.price * purchases.quantity) AS spend FROM purchases JOIN customers ON customers.id = purchases.customer_id JOIN albums ON albums.id = purchases.album_id GROUP BY customers.id, customers.name) SELECT name, ROUND(spend, 2) AS spend, ROUND(100.0 * SUM(spend) OVER (ORDER BY spend DESC, name ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) / SUM(spend) OVER (), 2) AS cumulative_pct FROM spending ORDER BY spend DESC, name",
			true,
			"trap",
			["business-metric", "window-function", "running-total", "ratio"],
		),
	],
};
