import { type AuthoredExercise, p } from "./practice-authoring";

export const dateTextAnalysisPractice: Record<string, AuthoredExercise[]> = {
	"date-text-analysis": [
		p(
			"pool-date-formation-decades",
			"Artists by formation decade",
			"Return each formation **decade** and artist count as **artist_count**, earliest decade first.",
			"Integer-divide formed_year by 10, then multiply by 10 before grouping.",
			"SELECT (formed_year / 10) * 10 AS decade, COUNT(*) AS artist_count FROM artists GROUP BY decade ORDER BY decade",
			true,
			"surface",
			["dates", "numeric-expressions", "grouping", "ordering"],
		),
		p(
			"pool-date-album-age-at-sale",
			"Album age when purchased",
			"For each purchase, show album **title**, **purchase_date**, and whole years since release as **album_age**. Sort by purchase date and title.",
			"Extract the purchase year as an integer and subtract release_year.",
			"SELECT albums.title, purchases.purchase_date, CAST(strftime('%Y', purchases.purchase_date) AS INTEGER) - albums.release_year AS album_age FROM purchases JOIN albums ON albums.id = purchases.album_id ORDER BY purchases.purchase_date, albums.title",
			true,
			"surface",
			["dates", "expressions", "multi-table", "ordering"],
		),
		p(
			"pool-date-days-between-orders",
			"Days between customer purchases",
			"For purchases after a customer's first, return **customer_id**, **purchase_date**, and whole **days_since_previous**. Sort by customer and date.",
			"Use LAG in a CTE, then filter out the first row and subtract julianday values.",
			"WITH timeline AS (SELECT customer_id, purchase_date, id, LAG(purchase_date) OVER (PARTITION BY customer_id ORDER BY purchase_date, id) AS previous_date FROM purchases) SELECT customer_id, purchase_date, CAST(julianday(purchase_date) - julianday(previous_date) AS INTEGER) AS days_since_previous FROM timeline WHERE previous_date IS NOT NULL ORDER BY customer_id, purchase_date, id",
			true,
			"surface",
			["dates", "lag", "cte", "expressions"],
		),
		p(
			"pool-text-email-domains",
			"Email domains",
			"Return each distinct email **domain** after `@`, alphabetically.",
			"instr finds @ and substr can start one character after it. DISTINCT removes repeats.",
			"SELECT DISTINCT substr(email, instr(email, '@') + 1) AS domain FROM customers ORDER BY domain",
			true,
			"surface",
			["string-functions", "distinct", "ordering"],
		),
		p(
			"pool-text-album-slugs",
			"Album URL slugs",
			"Convert each album title to lowercase with spaces replaced by hyphens. Return **title** and the result as **slug**, alphabetically by title.",
			"Nest lower(title) inside replace(..., ' ', '-').",
			"SELECT title, replace(lower(title), ' ', '-') AS slug FROM albums ORDER BY title",
			true,
			"neighbour",
			["string-functions", "function-composition", "ordering"],
		),
		p(
			"pool-text-customer-initials",
			"Customer initials",
			"Show customer **name** and two-letter **initials**, using the first letter and the first letter after the space. Sort by name.",
			"Use substr twice. instr(name, ' ') finds the start of the last name in this dataset.",
			"SELECT name, upper(substr(name, 1, 1) || substr(name, instr(name, ' ') + 1, 1)) AS initials FROM customers ORDER BY name",
			true,
			"neighbour",
			["string-functions", "string-concat", "ordering"],
		),
		p(
			"pool-text-long-title-lengths",
			"Long track names",
			"Return track **title** and character count as **characters** for titles longer than 12 characters, longest first.",
			"Use length(title) in both the projection and filter.",
			"SELECT title, length(title) AS characters FROM tracks WHERE length(title) > 12 ORDER BY characters DESC, title",
			true,
			"neighbour",
			["string-functions", "restriction", "ordering"],
		),
		p(
			"pool-date-weekdays",
			"Purchase weekday numbers",
			"For each purchase, return **id** and weekday number as **weekday**, where Sunday is 0. Sort by id.",
			"strftime('%w', purchase_date) returns the weekday as text. Cast it to INTEGER.",
			"SELECT id, CAST(strftime('%w', purchase_date) AS INTEGER) AS weekday FROM purchases ORDER BY id",
			true,
			"trap",
			["dates", "numeric-types", "ordering"],
		),
		p(
			"pool-date-join-years",
			"Customers by join year",
			"Return join **year** as an integer and **customer_count**, earliest year first.",
			"Extract with strftime, cast once, and group by the resulting year.",
			"SELECT CAST(strftime('%Y', joined_date) AS INTEGER) AS year, COUNT(*) AS customer_count FROM customers GROUP BY year ORDER BY year",
			true,
			"trap",
			["dates", "grouping", "numeric-types", "ordering"],
		),
		p(
			"pool-date-month-end",
			"Month-end date",
			"For each purchase, return **purchase_date** and that month's final date as **month_end**, sorted by purchase date.",
			"Move to start of month, add one month, then subtract one day.",
			"SELECT purchase_date, date(purchase_date, 'start of month', '+1 month', '-1 day') AS month_end FROM purchases ORDER BY purchase_date, id",
			true,
			"trap",
			["dates", "date-modifiers", "ordering"],
		),
	],
};
