import type { QueueCandidate } from "./exercise-queue";

function group(
	concept: string,
	pool: [id: string, difficulty: number][],
): QueueCandidate[] {
	return pool.map(([id, difficulty]) => ({ id, concept, difficulty }));
}

export const EXPANDED_POOL_CANDIDATES: QueueCandidate[] = [
	...group("null-handling", [
		["pool-null-release-status", 1],
		["pool-null-no-2023-sales", 2],
		["pool-null-album-buyers", 2],
		["pool-null-zero-revenue", 2],
		["pool-null-never-sold-artists", 2],
		["pool-null-total-units-by-artist", 2],
		["pool-null-purchased-only", 2],
		["pool-null-count-row-trap", 2],
		["pool-null-no-album-id", 1],
		["pool-null-bulk-or-zero", 2],
	]),
	...group("set-operations", [
		["pool-sets-people", 2],
		["pool-sets-all-countries", 2],
		["pool-sets-common-ids", 2],
		["pool-sets-not-sold-2023", 2],
		["pool-sets-shared-years", 2],
		["pool-sets-release-only-years", 2],
		["pool-sets-premium-purchased-genres", 2],
		["pool-sets-source-label", 2],
		["pool-sets-country-dedup-trap", 1],
		["pool-sets-union-all-count", 2],
	]),
	...group("self-joins", [
		["pool-self-album-chronology", 1],
		["pool-self-price-pairs", 1],
		["pool-self-consecutive-longer", 1],
		["pool-self-repeat-buyers", 1],
		["pool-self-same-day-basket", 0],
		["pool-self-country-seniority", 0],
		["pool-self-track-pairs", 1],
		["pool-self-no-mirrors", 0],
		["pool-self-adjacent-only", 1],
		["pool-self-cross-genre-pairs", 2],
	]),
	...group("advanced-aggregation", [
		["pool-agg-orders-vs-units", 1],
		["pool-agg-customer-order-size", 2],
		["pool-agg-genre-duration", 2],
		["pool-agg-artist-era-counts", 2],
		["pool-agg-genre-catalog-share", 2],
		["pool-agg-weighted-price", 1],
		["pool-agg-customer-span", 2],
		["pool-agg-genre-buyers", 2],
		["pool-agg-busy-expensive-genres", 2],
		["pool-agg-no-inflated-revenue", 1],
	]),
	...group("ctes", [
		["pool-cte-long-tracks", 2],
		["pool-cte-track-counts", 2],
		["pool-cte-customer-revenue", 3],
		["pool-cte-recursive-numbers", 2],
		["pool-cte-above-catalog-average", 2],
		["pool-cte-two-aggregates", 3],
		["pool-cte-best-months", 3],
		["pool-cte-one-definition", 1],
		["pool-cte-preserve-zeroes", 2],
		["pool-cte-calendar", 2],
	]),
	...group("correlated-subqueries", [
		["pool-corr-above-genre-average", 2],
		["pool-corr-below-album-average", 2],
		["pool-corr-latest-albums", 2],
		["pool-corr-world-customers", 2],
		["pool-corr-no-cairo-sales", 2],
		["pool-corr-only-single-copies", 3],
		["pool-corr-prolific-artists", 2],
		["pool-corr-priciest-by-genre", 2],
		["pool-corr-first-purchases", 2],
		["pool-corr-above-own-order-average", 2],
	]),
	...group("window-ranking", [
		["pool-rank-release-years", 1],
		["pool-rank-artist-release-order", 1],
		["pool-rank-longest-track-each", 2],
		["pool-rank-top-three-buyers", 3],
		["pool-rank-price-quartiles", 1],
		["pool-rank-customer-quantities", 1],
		["pool-rank-cheapest-genre", 2],
		["pool-rank-genres-by-average", 2],
		["pool-rank-purchase-sequence", 1],
		["pool-rank-duration-ties", 1],
	]),
	...group("window-analytics", [
		["pool-window-running-revenue", 1],
		["pool-window-customer-running-units", 1],
		["pool-window-quantity-change", 1],
		["pool-window-next-release-gap", 2],
		["pool-window-priciest-title", 1],
		["pool-window-track-moving-average", 1],
		["pool-window-unit-share", 1],
		["pool-window-cumulative-customer-share", 2],
		["pool-window-vs-customer-average", 1],
		["pool-window-repeat-count", 1],
	]),
	...group("date-text-analysis", [
		["pool-date-formation-decades", 1],
		["pool-date-album-age-at-sale", 1],
		["pool-date-days-between-orders", 2],
		["pool-text-email-domains", 1],
		["pool-text-album-slugs", 1],
		["pool-text-customer-initials", 1],
		["pool-text-long-title-lengths", 1],
		["pool-date-weekdays", 1],
		["pool-date-join-years", 1],
		["pool-date-month-end", 1],
	]),
	...group("business-analytics", [
		["pool-biz-repeat-customers", 2],
		["pool-biz-average-order-value", 1],
		["pool-biz-dormant-inventory", 2],
		["pool-biz-yearly-top-customer", 3],
		["pool-biz-monthly-revenue", 2],
		["pool-biz-genre-reach", 2],
		["pool-biz-basket-pairs", 2],
		["pool-biz-favorite-genres", 3],
		["pool-biz-artist-scorecard", 2],
		["pool-biz-cumulative-buyers", 2],
	]),
];
