import type { QueueCandidate } from "./exercise-queue";

export const CORE_LESSON_CANDIDATES: QueueCandidate[] = [
	{ id: "select-everything", concept: "select-basics", difficulty: 0 },
	{ id: "choosing-columns", concept: "select-basics", difficulty: 1 },
	{ id: "filtering-rows", concept: "select-basics", difficulty: 2 },
	{ id: "comparisons", concept: "select-basics", difficulty: 3 },
	{ id: "and-or", concept: "filtering-sorting", difficulty: 0 },
	{ id: "in-operator", concept: "filtering-sorting", difficulty: 1 },
	{ id: "like-patterns", concept: "filtering-sorting", difficulty: 2 },
	{ id: "order-by", concept: "filtering-sorting", difficulty: 3 },
	{ id: "limit", concept: "filtering-sorting", difficulty: 3 },
	{ id: "count", concept: "aggregates", difficulty: 0 },
	{ id: "avg", concept: "aggregates", difficulty: 1 },
	{ id: "group-by", concept: "aggregates", difficulty: 2 },
	{ id: "having", concept: "aggregates", difficulty: 3 },
	{ id: "inner-join", concept: "joins", difficulty: 0 },
	{ id: "join-filter", concept: "joins", difficulty: 1 },
	{ id: "multi-join", concept: "joins", difficulty: 2 },
	{ id: "left-join", concept: "joins", difficulty: 3 },
	{ id: "scalar-subquery", concept: "subqueries", difficulty: 0 },
	{ id: "in-subquery", concept: "subqueries", difficulty: 1 },
	{ id: "union", concept: "subqueries", difficulty: 2 },
	{ id: "case-when", concept: "expressions", difficulty: 0 },
	{ id: "string-concat", concept: "expressions", difficulty: 1 },
	{ id: "dates", concept: "expressions", difficulty: 2 },
	{ id: "capstone-revenue", concept: "expressions", difficulty: 3 },
];

export const CORE_POOL_CANDIDATES: QueueCandidate[] = [
	{ id: "pool-long-tracks", concept: "select-basics", difficulty: 0 },
	{ id: "pool-cairo-customers", concept: "select-basics", difficulty: 0 },
	{ id: "pool-budget-albums", concept: "select-basics", difficulty: 0 },
	{ id: "pool-recent-artists", concept: "select-basics", difficulty: 0 },
	{ id: "pool-folk-albums", concept: "select-basics", difficulty: 0 },
	{ id: "pool-not-usa", concept: "select-basics", difficulty: 0 },
	{ id: "pool-rock-or-folk", concept: "filtering-sorting", difficulty: 1 },
	{ id: "pool-light-tracks", concept: "filtering-sorting", difficulty: 0 },
	{ id: "pool-joined-2023", concept: "filtering-sorting", difficulty: 1 },
	{ id: "pool-mid-price", concept: "filtering-sorting", difficulty: 1 },
	{ id: "pool-synthpop-recent", concept: "filtering-sorting", difficulty: 0 },
	{
		id: "pool-five-letter-tracks",
		concept: "filtering-sorting",
		difficulty: 0,
	},
	{ id: "pool-cheapest-three", concept: "filtering-sorting", difficulty: 1 },
	{ id: "pool-albums-per-genre", concept: "aggregates", difficulty: 1 },
	{ id: "pool-avg-price-per-artist", concept: "aggregates", difficulty: 1 },
	{ id: "pool-quantity-per-customer", concept: "aggregates", difficulty: 1 },
	{ id: "pool-longest-per-album", concept: "aggregates", difficulty: 1 },
	{ id: "pool-pricey-genres", concept: "aggregates", difficulty: 2 },
	{
		id: "pool-distinct-genres-per-artist",
		concept: "aggregates",
		difficulty: 1,
	},
	{ id: "pool-genre-list", concept: "aggregates", difficulty: 0 },
	{ id: "pool-units-not-orders", concept: "aggregates", difficulty: 1 },
	{ id: "pool-album-artist", concept: "joins", difficulty: 1 },
	{ id: "pool-track-album", concept: "joins", difficulty: 1 },
	{ id: "pool-customer-purchases", concept: "joins", difficulty: 1 },
	{ id: "pool-artist-tracks", concept: "joins", difficulty: 1 },
	{ id: "pool-every-artist-albums", concept: "joins", difficulty: 2 },
	{ id: "pool-artists-no-albums", concept: "joins", difficulty: 1 },
	{ id: "pool-track-matching-album", concept: "joins", difficulty: 1 },
	{ id: "pool-same-city-customers", concept: "joins", difficulty: 1 },
	{ id: "pool-above-average-price", concept: "subqueries", difficulty: 2 },
	{ id: "pool-artists-with-albums", concept: "subqueries", difficulty: 2 },
	{
		id: "pool-longer-than-album-average",
		concept: "subqueries",
		difficulty: 2,
	},
	{ id: "pool-no-albums-not-exists", concept: "subqueries", difficulty: 2 },
	{ id: "pool-world-buyers", concept: "subqueries", difficulty: 2 },
	{ id: "pool-top-buyers", concept: "subqueries", difficulty: 3 },
	{ id: "pool-released-since-2015", concept: "subqueries", difficulty: 2 },
	{ id: "pool-price-bands", concept: "expressions", difficulty: 0 },
	{ id: "pool-artist-label", concept: "expressions", difficulty: 1 },
	{ id: "pool-purchase-years", concept: "expressions", difficulty: 1 },
	{ id: "pool-track-minutes", concept: "expressions", difficulty: 0 },
	{ id: "pool-decade-label", concept: "expressions", difficulty: 1 },
	{ id: "pool-first-half-joiners", concept: "expressions", difficulty: 1 },
	{ id: "pool-minutes-and-seconds", concept: "expressions", difficulty: 0 },
];
